name: auto-label
on:
  pull_request

jobs:
  auto-label:
    runs-on: windows-latest
    steps:
    - uses: actions/labeler@v2
      with:
        CORE: core/**/*
        UI: frontend/**/*
        BACKEND: backend/**/*
        ROOT_CHECK: ./*
        README: ./*.md
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
